[package]
name = "arfpack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.61"
binrw = "0.9.2"
clap = { version = "3.2.17", features = ["derive"] }
walkdir = "2.3.2"

[features]
